### PR TITLE
Show path for schema errors

### PR DESCRIPTION
**Pull request by sporto**
I tried decoding our schema.

And it fails with an error like 
```gleam
Error(UnexpectedFormat([DecodeError(expected: "another type", found: "Object", path: ["schemas",  "values"])]))
```

This is comming from the dictionary decoder, which doesn't give enough information about the value that is failing.

Our schema fails because some schema are missing the `type` property.
It is quite hard to figure out where as it is quite large.

This is an attempt at providing more information (they key of the dictionary that fails):

```gleam
Error(UnexpectedFormat([DecodeError(expected: "another type", found: "Object", path: ["schemas",  "thing"])]))
```

### CODE REVIEW

**Comment by CrowdHailer** [comment]
Should we make the suggestion that this is how `dynamic.dict` should work anyway?
I see the benefit and I like the test coverage, but I'm slight reluctant to support this patch to decoding.

**Comment by sporto** [comment]
I agree that the dynamic dict decoder should do something like this. I will look into it. 
But that could take a while. In the meantime it would be great to have something here that can show an informative error.

**Comment by sporto** [comment]
Looking at std https://github.com/gleam-lang/stdlib/blob/main/src/gleam/dynamic.gleam#L968
It seems it will be much simpler to show the informative error there. So let's hold on this PR.

**Comment by sporto** [comment]
https://github.com/gleam-lang/stdlib/pull/741

This will show `values[index]`.
Not really possible to show the key name in the standard lib I think.

But we could do better here by showing the key name. As the key is a string.

**Comment by CrowdHailer** [comment]
alight lets go for it. thanks for the investigation

**Pull request merged**
